In [2]:
import spacy
import pandas as pd
import numpy as np
import csv
from datetime import datetime
nlp = spacy.load("en_core_web_sm")

In [5]:
dataset = pd.read_csv('../data/upworthy-confirmatory.csv', low_memory=False, usecols=[*range(3,4),*range(5,6),*range(9,11)])

In [12]:
dataset.head(20)

,clickability_test_id,headline,impressions,clicks,contains_entity
0,546dd17e26714c82cc00001c,"Let’s See … Hire Cops, Pay Teachers, Buy Books...",3118,8,0
1,546e01d626714c6c4400004e,People Sent This Lesbian Questions And Her Rai...,4587,130,0
2,546dd17e26714c82cc00001c,$3 Million Is What It Takes For A State To Leg...,3017,19,0
3,546dd17e26714c82cc00001c,The Fact That Sometimes Innocent People Are Ex...,2974,26,0
4,546dd17e26714c82cc00001c,Reason #351 To End The Death Penalty: It Costs...,3050,10,0
5,546dd17e26714c82cc00001c,"I Was Already Against The Death Penalty, But N...",3061,20,0
6,546dd17e26714c82cc00001c,I'll Say It: It's Not OK For States To Legally...,2997,20,0
7,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,2959,29,0
8,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,3086,16,0
9,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,3068,16,0
10,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,2988,19,0
11,546e0d339ad54e667a00005a,You Guys. Solar-Powered Boat Schools. Repeat. ...,4596,14,0
12,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,3039,15,0
13,546dd73684ad3817bc000048,The Fact That Sometimes Innocent People Are Ex...,3116,39,0
14,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,2939,47,0
15,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,3036,17,0
16,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,3111,28,0
17,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,2995,9,0
18,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,3063,22,0
19,546ddc5b26714c856600002c,The Fact That Sometimes Innocent People Are Ex...,3095,10,0

In [6]:
dataset['impressions'] = dataset['impressions'].astype('int')
dataset['clicks'] = dataset['clicks'].astype('int')

In [7]:
dataset["contains_entity"] = 0

In [8]:
df = pd.DataFrame(columns=["test_id","headline","impressions","clicks","contains_entity"])

In [9]:
df.head()

Empty DataFrame
Columns: [test_id, headline, impressions, clicks, contains_entity]
Index: []

In [8]:
for i in range(0,len(dataset)):
    test = dataset.iloc[i]["clickability_test_id"]
    headline = dataset.iloc[i]["headline"]
    impressions = dataset.iloc[i]["impressions"]
    clicks = dataset.iloc[i]["clicks"]
    doc = nlp(headline)
    if len(doc.ents) != 0:
        newRow = [test,headline,impressions,clicks,1]
    else:
        newRow = [test,headline,impressions,clicks,0]
    df.loc[len(df)] = newRow

In [ ]:
dataset

In [ ]:
df.to_csv('contains_entities.csv', index= False)

In [ ]:
df[1:20]